#pragma once

#define TIIVISTEMATTI_MAJOR 1
#define TIIVISTEMATTI_MINOR 0
#define TIIVISTEMATTI_BUILD 1917

// See .github/actions/msvc.yml - this value should not be set manually
#define TIIVISTEMATTI_COMMIT_HASH "to-be-set-in-a-build-pipeline"

#define TIIVISTEMATTI_STRINGIFY_INNER(x) #x
#define TIIVISTEMATTI_STRINGIFY_OUTER(x) TIIVISTEMATTI_STRINGIFY_INNER(x)

#define TIIVISTEMATTI_VERSION \
	TIIVISTEMATTI_STRINGIFY_OUTER(TIIVISTEMATTI_MAJOR) "." \
	TIIVISTEMATTI_STRINGIFY_OUTER(TIIVISTEMATTI_MINOR) "." \
	TIIVISTEMATTI_STRINGIFY_OUTER(TIIVISTEMATTI_BUILD)

#define TIIVISTEMATTI_VERSION_LONG \
	TIIVISTEMATTI_STRINGIFY_OUTER(TIIVISTEMATTI_MAJOR) "." \
	TIIVISTEMATTI_STRINGIFY_OUTER(TIIVISTEMATTI_MINOR) "." \
	TIIVISTEMATTI_STRINGIFY_OUTER(TIIVISTEMATTI_BUILD) ".0"
