#pragma once

#define HASHCALC_MAJOR 1
#define HASHCALC_MINOR 0
#define HASHCALC_BUILD 1917

// See .github/actions/msvc.yml - this value should not be set manually
#define HASHCALC_COMMIT_HASH "to be set in a build pipeline"

#define HASHCALC_STRINGIFY_INNER(x) #x
#define HASHCALC_STRINGIFY_OUTER(x) HASHCALC_STRINGIFY_INNER(x)

#define HASHCALC_VERSION \
	HASHCALC_STRINGIFY_OUTER(HASHCALC_MAJOR) "." \
	HASHCALC_STRINGIFY_OUTER(HASHCALC_MINOR) "." \
	HASHCALC_STRINGIFY_OUTER(HASHCALC_BUILD)

#define HASHCALC_VERSION_LONG \
	HASHCALC_STRINGIFY_OUTER(HASHCALC_MAJOR) "." \
	HASHCALC_STRINGIFY_OUTER(HASHCALC_MINOR) "." \
	HASHCALC_STRINGIFY_OUTER(HASHCALC_BUILD) ".0"
