name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
    - uses: actions/checkout@v6
    - uses: microsoft/setup-msbuild@v3
    - uses: darenm/Setup-VSTest@v1.2

    - name: Version
      shell: pwsh
      run: |
        (Get-Content "Version.h" -Raw).Replace("1917", "${{ github.run_number }}").Replace("to be set in a build pipeline", "${{ github.sha }}") | Set-Content "Version.h"
        (Get-Content "TiivisteMattiInstaller/TiivisteMattiInstaller.wxs" -Raw).Replace("1917", "${{ github.run_number }}") | Set-Content "TiivisteMattiInstaller/TiivisteMattiInstaller.wxs"

    - name: Compile
      run: |
        msbuild TiivisteMatti.sln /m /p:Configuration=Debug
        msbuild TiivisteMatti.sln /m /restore /p:Configuration=Release

    - name: Test
      run: |
        vstest.console.exe out/x86d/bin/TiivisteMattiTests.dll
        vstest.console.exe out/x64d/bin/TiivisteMattiTests.dll

    - name: Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automated release (latest commit, x64 only)"
          files: |
            out/x64/bin/*.exe
            out/x64/bin/*.msi
