name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - uses: microsoft/setup-msbuild@v3
    - uses: darenm/Setup-VSTest@v1.2

    - name: Version
      run: |
        (Get-Content "Version.h" -Raw).Replace("1917", "${{ github.run_number }}").Replace("to be set in a build pipeline", "${{ github.sha }}") | Set-Content "Version.h"

    - name: Compile
      run: |
        msbuild Win32HashCalc.sln /m

    - name: Test
      run: |
        vstest.console.exe out/x86d/bin/HashCalcTests.dll
        vstest.console.exe out/x64d/bin/HashCalcTests.dll